### ISSUE TITLE
Energy calibration for flash

### ISSUE THREAD

**Issue by yacremann** [OpenCOMPES/sed#102]
For operation at FLASH we developed a calibration method of the energy calibration (it is part of the hextof processor). It would be great to have the same functionality in SED.

**Comment by rettigl** [comment]
The calibration fitting functions presently there should also work for FLASH bias series. You can also directly supply the calibration parameters to the function. How did you perform energy calibration at FLASH before? I would prefer if we find a common solution, so that we don't have multiple functions for doing similar things.

**Comment by steinnymir** [comment]
We are currently working on implementing the corrections and calibrations from `hextof-processor`, but are currently still not available.

The principle behind the energy calibration there was to transform the time-of-flight to an energy scale, based on photon energy, sample bias and tof bias, all from measured quantities. Optionally these could be also fixed values.

This has the advantage of correcting for possible fluctuations in the photon energy, but also has some drawbacks. In particular, the electron path is assumed constant for all energies and detected angles, which is a rough approximation.

I believe we should implement at first all the hextof and all the MPES methods and make them easily callable. Then we can select which to prioritize or try to combine them when possible.

**Comment by rettigl** [comment]
I think you should be able to get a similar result by adjusting the offset parameter accordingly. But off course you can add another method to the function as well. I would just like to avoid that we have multiple functions and/or modules that do more or less the same. This will confuse users.

**Comment by steinnymir** [comment]
I agree that we should try avoid multiple functions doing the same thing, but also loosing functionality from other methods because one is already implemented is not ideal.

having two different approaches that to do similar things, does not make them interchangeable. There are some corrections necessary for FLASH data which do not fit in the workflow for MPES (sector correction for example).

I believe a good starting point is to provide different workflow methods which can be applied at will on a workflow manager. This can then be tuned to use the preferred methods for each experiment.
I will explain this in more detail in our meeting Tuesday.

**Comment by zainsohail04** [comment]
Hi @steinnymir, any updates on the workflow feature? Dima was saying we need the calibration functions soon so I was wondering if we should try implementing them in the current state or with the workflow feature.

**Comment by steinnymir** [comment]
hi @zainsohail04, I am still at an early stage of the infrastructure, but I think I could make the pull request soon. There will still be many things to implement to get a full, flexible workflow though.

When is the beamtime starting?

**Comment by steinnymir** [comment]
a first basic version is in the pull request #104

**Comment by kutnyakhov** [comment]
Beamtime is already running until Tuesday morning and @zainsohail04 and @steinnymir you should have access to the data (/asap3/flash/gpfs/pg2/2023/data/11013426) in case something has to be tested.

**Comment by kutnyakhov** [comment]
I've prepared a notebook with an example of how we did energy calibration at FLASH, but somehow I could not find a proper way to add to this discussion :)

**Comment by kutnyakhov** [comment]
I've added all to DESY cloud
https://syncandshare.desy.de/index.php/s/Fn9GWHF3yoyAyyN

**Comment by rettigl** [comment]
It appears this was done with quite some outdated version of sed, no? I could get it to run now with updating at some places, and it seems more or less straight forward to include, but there are a few things to consider.
1. How do we want to take the photon energy into account? So far, this is included into the calibration parameters by defining the energy of the calibration feature (the energy offset). This is fine as long as the photon energy is constant, but at FLASH it is not.
2. Where do we make the decision about the energy scale direction (i.e. binding/kinetic)? Right now, I flip the sign of the calibration function, but you rather flip the sign of the applied energy axis later. We could consider opting for one way to define the calibration, and move the switch on energy scale into the actual calibration function, thus having the flexibility at application time. I kind of like this idea.
3. Automatically including the bias offset into the calibration should be straight forward, I will also add another offset parameter there, that allows to easily adjust the (stored) calibration at application time.

**Comment by rettigl** [comment]
Being developed in PR #152

**Comment by steinnymir** [comment]
solved in #169 and #152
