### ISSUE TITLE
Add more options for defining bins from ranges

### ISSUE THREAD

**Issue by rettigl** [OpenCOMPES/sed#123]
Let's thiscuss which of these options whe want to add:
-including the endpoint
-providing the stepsize
-providing/returning the bin edges rather than bin centers

**Comment by steinnymir** [comment]
I think this depends also on what part of the code should be returning this.
If we are talking about the binning functions, those should behave as similar as possible to np.histogramdd. 
If we are instead talking about the processor method to add axes to bin on, and the binning method itself, I would sick to the xarray output, and think of which is the most logical input, and as discussed, return an xarray with bin centers (or Interval objects) as coordinates.

**Comment by rettigl** [comment]
@steinnymir how do you consider the interface for this to look like? Should we add an additional parameter bin_size? Or should we adopt the functionality as is described in the docstring (tuple of start, end, stepsize instead of the current implementation of start, end, num_points)?
