### ISSUE TITLE
Improve channel joining in FlashLoader 

### ISSUE THREAD

**Issue by zain-sohail** [OpenCOMPES/sed#128]
Is this sparse and dense channels likewise? Is it mist efficient doing it this way (creating lots of dataframe and joining?)

_Originally posted by @rettigl in https://github.com/OpenCOMPES/sed/pull/118#discussion_r1212268625_

Improvement in concatenate channels can be made to the join operation.

**Comment by zainsohail04** [comment]
I had a brief look into this. Most of the time is spend merging the dataframes. I think this very inefficient. But I don't know if it can be done better with your multi-index stuff. Creating the per-electron multi-index also takes some time. How long does this example file take on maxwell, and what is the hardware there?

_Originally posted by @rettigl in https://github.com/OpenCOMPES/sed/pull/118#discussion_r1213632524_

**Comment by zain-sohail** [comment]
I think this is a nice improvement but currently not really slowing us majorly. Shall I look into this or put is as wontfix @rettigl @steinnymir

**Comment by steinnymir** [comment]
I agree, the timing for generating the dataframe currently is really fast, so this is not really an issue worth investing on.

**Comment by rettigl** [comment]
This essentially is parallelized very efficiently, so also from my side no real need to further improve. The major game changer was the improvements done to the fill_na. Closing this.
