### ISSUE TITLE
Calibrate delay axis

### ISSUE THREAD

**Issue by kutnyakhov** [OpenCOMPES/sed#130]
I am getting an error message while trying to calibrate_delay_axis.
It is looking for an ADC channel
KeyError: 'ADC'
which is not existing in our/FLASH files.
Even if I am trying to add as a parameter time0 and delay_range
sp.calibrate_delay_axis(time0=1463.6, delay_range=delay_range)
it is still looking for adc_range[0], adc_range[1], df[adc_column]

**Comment by rettigl** [comment]
Yes, this function is specific to our imlementation converting the ADC channel into delay coordinates. I am not sure how the current version for flash has to look like (which channels have to be used). It would be good if we can come up with a combined function that does the correct thing depending on the config values.

**Comment by rettigl** [comment]
Same applies probably for energy and momentum calibration functions for FLASH, as discussed previously. I am happy to help if I know why you guys need and want to use.

**Comment by kutnyakhov** [comment]
> 

At FLASH, we are getting direct encoder position value in ps in our data stream (delayStage channel), so conversion is unnecessary. With hextof-processor we've used just time0 and delay range values for calibration.

**Comment by rettigl** [comment]
I remember there was quite some elaborate code for e.g. filtering backwards/forwards scanning data, and also BAM correction etc. Is this all not required anymore? I suggest @zainsohail04 and/or @steinnymir, who know the FLASH code best, to have a look at this, and either suggest an independent function for FLASH, or integrate it with the mpes function (the funcionality could e.g. be made dependent on the availability of certain dataframe columns, or also simply the employed reader).
