### ISSUE TITLE
config error when passing kwds for loader

### ISSUE THREAD

**Issue by zain-sohail** [OpenCOMPES/sed#153]
Certain kwds need to be passed when creating an instance as shown below
`SedProcessor(runs=46082, config="N3_Dye_2023_1Q.yaml", collect_metadata=True, detector="1Q", save_parquet=True)
`
Since the config takes kwds but only specific ones
`self._config = parse_config(config, **kwds)`
it is throwing a type error: 
`TypeError: parse_config() got an unexpected keyword argument <...>`

**Comment by rettigl** [comment]
This one is being addressed in PR #143 
Please confirm that it works there.

**Comment by zain-sohail** [comment]
Tested and PR https://github.com/OpenCOMPES/sed/pull/143 fixes this bug.
