### ISSUE TITLE
Tests for flash loader and metadata

### ISSUE THREAD

**Issue by zain-sohail** [OpenCOMPES/sed#154]
This whole branch is not being tested for. I think it would be good to write a separate test for it, but could be done later.

_Originally posted by @rettigl in https://github.com/OpenCOMPES/sed/pull/133#discussion_r1340976311_
            

              There are no tests for metadata yet. I think mpes metadata are tested partly through the processor tests, maybe you can do something similar, or add a generic metadata test in test_loader?

_Originally posted by @rettigl in https://github.com/OpenCOMPES/sed/pull/133#discussion_r1341004667_

**Comment by rettigl** [comment]
done by PR #239
