### ISSUE TITLE
Tutorials requiring mpes

### ISSUE THREAD

**Issue by zain-sohail** [OpenCOMPES/sed#157]
https://github.com/OpenCOMPES/sed/blob/bdd041ff3841153017f70688b45a01b8872e639e/tutorial/2%20-%20Binning%20of%20example%20time-resolved%20ARPES%20data.ipynb#L27

Is this purposeful or was done before, when sed didn't have all methods?

I am trying to automate documentation generation currently as mentioned in #155

**Comment by rettigl** [comment]
This was added in tutorial 2 to verify sed gives the same result and performance as mpes. We can remove it there, and move it into a benchmark notebook. But keeping mpes as as requirement for the docs should be fine, no?

**Comment by zain-sohail** [comment]
Yes I would agree if it goes into a benchmarks section. I'd argue it doesn't stay in tutorials but maybe a seperate folder called benchmarks and we can put those benchmarks in the documentation as well.

**Comment by rettigl** [comment]
has been removed
