### ISSUE TITLE
Save and load a dataframe (for testing purposes)

### ISSUE THREAD

**Issue by steinnymir** [OpenCOMPES/sed#16]
Its very important to have an easy access save/load functionality for the dataframe.

This should be also implmeneted for multiple file formats (parquet,hdf5,...)

**Comment by steinnymir** [comment]
The most important formats to start with are hdf5 and .tiff
for HDF5 we need to discuss a standard structure and namings, but having some simple starting point soon is better than a perfect system later.
.tiff stacks are important for the first user case we will deploy to, which require .tiff stacks to perform their analysis.

**Comment by daviddoji** [comment]
Regarding h5 files, I would be as general as possible. 
Ideally, I'd like to be able to open h5 files with the European XFEL library (https://github.com/European-XFEL/EXtra-data) and continue the analysis from there.

**Comment by steinnymir** [comment]
Excellent starting point @rettigl, we might think of a better group structure, but that is not super-urgent.
I am not familiar with the EXtra-data format, but would agree we must provide output for that one too.
@daviddoji, would you be willing to write the converter function for that format?

**Comment by daviddoji** [comment]
> Excellent starting point @rettigl, we might think of a better group structure, but that is not super-urgent. I am not familiar with the EXtra-data format, but would agree we must provide output for that one too. @daviddoji, would you be willing to write the converter function for that format?

I guess that we agree on that the logic for the computation has to be independent from the logic of reading h5 files.
No matter how you read the files, the output of this reading process has to be identical for whatever format/facility, so we can fed the results directly to the computation logic.

I would need to know a couple of things before writing the "converter" function:
- how and what the EuXFEL DAQ saves into files?
- which data is needed for the computation?

First question is still under discussion, as we don't still have a detector in place at EuXFEL. For the second question, I asked you for a quick chat ;)
