### ISSUE TITLE
FLASH loader issues and feature request

### ISSUE THREAD

**Issue by steinnymir** [OpenCOMPES/sed#160]
Here is a list of issues which need fixing in the hextof loader. Further requirements will be added over time.

 - [ ] #170
 - [x] improve performance of fillna. Need to find a smarter way which does not require reading the entire data to do this, or at least keep it lazy until binning or saving the dataframe.
 - [x] find channel which contains info about detector section (what used to be the 3 bits in dldToF
 - [x] save parquets

**Comment by zain-sohail** [comment]
Regarding fillna, currently we have the buffers being created. We were keeping them to have data loading be faster. But if that's not necessary, we can think up of a way.

Number 1 exists here https://github.com/OpenCOMPES/sed/blob/8f49f40b59d7927e644183fa3bad61b39dd9d5ff/sed/loader/flash/loader.py#L546

and number 4 here
https://github.com/OpenCOMPES/sed/blob/8f49f40b59d7927e644183fa3bad61b39dd9d5ff/sed/loader/flash/loader.py#L733

**Comment by zain-sohail** [comment]
> > When the buffers already exist, the fill_na method is indeed lazy
> 
> I don't think so. You compute every data frame part in fill_na, and that is not lazy as far as I can tell. It indeed also takes almost as long to load data even if the buffer files are already there

Oh you are right. There is this line https://github.com/OpenCOMPES/sed/blob/8f49f40b59d7927e644183fa3bad61b39dd9d5ff/sed/loader/flash/loader.py#L714 and another that has compute in them. 
There is now a possiblity to save concatenated parquet so at least that'd speed up the loading. But it shouldn't take as long to load data with buffer files

**Comment by steinnymir** [comment]
I added these points after extended tests on trying to load old data.

> Number 1 exists here
> 
> https://github.com/OpenCOMPES/sed/blob/8f49f40b59d7927e644183fa3bad61b39dd9d5ff/sed/loader/flash/loader.py#L546

This does not answer the problem. Providing non existing h5 addresses (channels) the code runs through until saving the parquets, it even thinks it did taht succesfully but then fails at reading them.
A check is needed at the beginning, which opens one of the files and checks that channels exist and have the correct shape.

Regarding the fillna, as @rettigl said, it is extremely slow. it takes 10-20 minutes to load larger runs. We need to think about how this can be improved, and if this can be made entirely lazy (zero-read version of fillna)




> and number 4 here
> 
> https://github.com/OpenCOMPES/sed/blob/8f49f40b59d7927e644183fa3bad61b39dd9d5ff/sed/loader/flash/loader.py#L733

Is this a valid way to save the dataframe after loading it in SedProcessor? should there not rather be a `SedProcessor.save_dataframe()` method?

**Comment by rettigl** [comment]
> Regarding the fillna, as @rettigl said, it is extremely slow. it takes 10-20 minutes to load larger runs. We need to think about how this can be improved, and if this can be made entirely lazy (zero-read version of fillna)

Could the fill_nan already be applied to the saved parquets, and saved as part of those? Alternatively, mabye an approach with delayed dask arrays, and conversion into dask dataframes with .from_delayed() as we use in the mpes loader might work to make this function lazy.

**Comment by steinnymir** [comment]
The difficulty was in the necessity to read data from neighbouring chuncks, but there might be a solution for that. I'll have a look how you do it in the mpes loader

**Comment by zain-sohail** [comment]
> > Regarding the fillna, as @rettigl said, it is extremely slow. it takes 10-20 minutes to load larger runs. We need to think about how this can be improved, and if this can be made entirely lazy (zero-read version of fillna)
> 
> Could the fill_nan already be applied to the saved parquets, and saved as part of those? Alternatively, mabye an approach with delayed dask arrays, and conversion into dask dataframes with .from_delayed() as we use in the mpes loader might work to make this function lazy.

That's of course possible but I recall it increases the file size significantly.


> Regarding the fillna, as @rettigl said, it is extremely slow. it takes 10-20 minutes to load larger runs. We need to think about how this can be improved, and if this can be made entirely lazy (zero-read version of fillna)

> The difficulty was in the necessity to read data from neighbouring chuncks, but there might be a solution for that. I'll have a look how you do it in the mpes loader

please take a look at PR #162 @steinnymir 




> This does not answer the problem. Providing non existing h5 addresses (channels) the code runs through until saving the parquets, it even thinks it did taht succesfully but then fails at reading them. A check is needed at the beginning, which opens one of the files and checks that channels exist and have the correct shape.

That is very odd. Because that is exactly doing what you want: 

https://github.com/OpenCOMPES/sed/blob/8f49f40b59d7927e644183fa3bad61b39dd9d5ff/sed/loader/utils.py#L54

Opens file and checks which channels are present.

and then it compares it with the channels provided in config and if it doesn't exist, gives a value error:
https://github.com/OpenCOMPES/sed/blob/8f49f40b59d7927e644183fa3bad61b39dd9d5ff/sed/loader/flash/loader.py#L555

Maybe there is a logic error here and we can figure it out.


> Is this a valid way to save the dataframe after loading it in SedProcessor? should there not rather be a `SedProcessor.save_dataframe()` method?

So far there was no issues with it. It was created for the wespe instrument as we need to save and load parquets after simulating and augmneting the data. But we can also go that direction. That however would not fall under a FlashLoader issue then because it'd be part of processor?

**Comment by rettigl** [comment]
> That is very odd. Because that is exactly doing what you want:
> 
> https://github.com/OpenCOMPES/sed/blob/8f49f40b59d7927e644183fa3bad61b39dd9d5ff/sed/loader/utils.py#L54

I must agree with @steinnymir, this code does not do what it is intended for. I'm not sure why not, maybe because of the paralellization. This once more illustrates the importance to write proper tests for every branch of code you write...

**Comment by steinnymir** [comment]
I am closing this and keepin an issue for the only remaining element: #170
