### ISSUE TITLE
Flash jitter config

### ISSUE THREAD

**Issue by rettigl** [OpenCOMPES/sed#163]
Jittering for Flash dldTime does not work with the normal settings correctly. The reason I believe could be that due to the 4-quadrant DLD, consequative entries in each quadrant are separated by 4 integers, and thus would need jitter amplitude=2.

**Comment by rettigl** [comment]
@steinnymir The code you put into the 8s_... delay stuff solves this issue I think, however only if we apply the delay on the level of bins, rather than ns, and leave the conversion to ns to the energy calibration function. I would propose to put the 8s... coversion actually into the flash loader, and always execute it if configured in the loader (is there a flag in the files we can use to detect if we have such a detector?) because the dldTime without the conversion does not make any sense anyways.

**Comment by steinnymir** [comment]
For the time being we are collecting methods in the SedProcessor. When things are working we can see if they live better in the loader as you suggested.

I will move everything to the right place before the PR

**Comment by steinnymir** [comment]
oh and this will require a "jitter amp" parameter to be passed in the config, so that the tof_channel of hextof can be jittered correctly, properly solving this issue

**Comment by rettigl** [comment]
> oh and this will require a "jitter amp" parameter to be passed in the config, so that the tof_channel of hextof can be jittered correctly, properly solving this issue

Well, my point is that if you jitter _after_ sorting out the channels, and correcting on the level of bins, and _before_ converting into ns, you can still jitter half a bin...

**Comment by rettigl** [comment]
Then it's consistent with the other loaders

**Comment by steinnymir** [comment]
no, the half bin still doesn't work. The dldTime channel is in units of steps, but the real digial signal there is 8 times bigger, as the first 3 bits are overwritten to encode the sector ID. Therefore, with the channel correcly in steps, the jitter needs amplitude of 4 steps not .5

**Comment by steinnymir** [comment]
alternatively, these conversions can be done including one which changes the step size to be 8 times larger, and changing the step_to_nanosecond parameter value

**Comment by steinnymir** [comment]
No, I thought I needed to, but I don't in the later version, for similarity to how this was done previously. I might revert this though

**Comment by steinnymir** [comment]
in #169 the dldTimeSteps column is now in units of 1 step. Jittering works as in all other channels, with no requirement for an amplitude parameter passed.
