### ISSUE TITLE
Add dtype in loaders

### ISSUE THREAD

**Issue by steinnymir** [OpenCOMPES/sed#172]
Some columns are saved as float64 in raw data when this precision is not necessary. It might be beneficial to add a `dtype` option in the channels in the settings which tells which format to save the data to, and converting on readout.

This is particularly relevant for the FLASH Loader

**Comment by rettigl** [comment]
This sounds like a good idea for saving space in the parquet files

**Comment by zain-sohail** [comment]
I included this in the new PRs #329 and #330  (is the config model for loaders)

**Comment by rettigl** [comment]
closed by #329 and #411
