### ISSUE TITLE
kinetic vs binding energy sign

### ISSUE THREAD

**Issue by balerion** [OpenCOMPES/sed#175]
**Is your feature request related to a problem? Please describe.**
I would highly appreciate the possibility of having a binding energy axis with the same sign as the kinetic energy axis when using the append_energy_axis function. This is because many fitting functions and post data analysis steps require the negative binding energy convention, with the Fermi edge closer to 0 eV.

**Describe the solution you'd like**
add optional override "sign" or "prefactor" parameter in tof2ev function. It would be useful if this could be an arbitrary constant, so this could also be used to correct for the fact that the time channel can be in ns rather than s

**Describe alternatives you've considered**
I tried using an imaginary unit multiplied by the tof_distance parameter, but this gives all sorts of problems.

**Additional context**
-

**Comment by rettigl** [comment]
The values for energy_scale only determine the direction of increasing energy, not an absolute energy scale, see the docscring:
```
energy_scale (str, optional) –
Direction of increasing energy scale.
    ’kinetic’: increasing energy with decreasing TOF.
    ’binding’: increasing energy with increasing TOF.
```
Thus, what you want is actually what we also typically do, by selecting energy_scale="kinetic", and choosing an appropriate energy offset during calibration to get E-E_F energy scaling. We will introduce an additional shift_energy_axis function shortly, that will allow for doing this conveniently after energy calibration.

We should add appropriate documentation for this once completed.

**Comment by rettigl** [comment]
> add optional override "sign" or "prefactor" parameter in tof2ev function. It would be useful if this could be an arbitrary constant, so this could also be used to correct for the fact that the time channel can be in ns rather than s

I think the standard way should be to convert tof_bins into energy directly, and using the new convert_to_ns function for doing the conersion to ns. Alternatively, one could also provide the option to convert directly from a ns channel, but that should not be the standard.

**Comment by balerion** [comment]
> The values for energy_scale only determine the direction of increasing energy, not an absolute energy scale, see the docscring:
> 
> ```
> energy_scale (str, optional) –
> Direction of increasing energy scale.
>     ’kinetic’: increasing energy with decreasing TOF.
>     ’binding’: increasing energy with increasing TOF.
> ```
> 
> Thus, what you want is actually what we also typically do, by selecting energy_scale="kinetic", and choosing an appropriate energy offset during calibration to get E-E_F energy scaling. We will introduce an additional shift_energy_axis function shortly, that will allow for doing this conveniently after energy calibration.
> 
> We should add appropriate documentation for this once completed.

Yes, this is close to what i would like. but, when reading the metadata, it says "kinetic" and then one risks wrongly flipping the axis again in post analysis. So perhaps a different option is to remove the keyword "kinetic" and change it to something different? like "energy_direction_positive"

**Comment by rettigl** [comment]
> change it to something different? like "energy_direction_positive"

Is this better defined? we can discuss how to call this, but these two terms were so far the best fitting that came to my mind. Maybe it just needs better documentation?

**Comment by steinnymir** [comment]
One solution could be renaming `energy_scale` to somethig more specific:
 -  `energy_axis_direction`, which should already remind the reader this does not define the axis entirely. The values could even be `kinetic-like` and `binding-like` for example to avoid confusion.

- `binding_energy_direction` with `positive` and `negative` could also work. This is rather self-explainatory.

In any case a good documentation will always be needed.
This however is fine for the code side, but the confusion might remain if someone only looks at the data and metadata, without looking up sed documentation.

This might be true for many other parameters so we might want to discuss adding descriptions to the metadata we save.

**Comment by balerion** [comment]
> * `binding_energy_direction` with `positive` and `negative` could also work. This is rather self-explainatory.

I personally would find this option super intuitive and i really like it, also considering going back to the data in the future and eventually improving readability of data on open databases
