### ISSUE TITLE
Fix energy calibration parameters

### ISSUE THREAD

**Issue by steinnymir** [OpenCOMPES/sed#208]
@rettigl Is is currently possible to fix a parameter in the energy calibration fit function?

At FLASH we would like to use this to fix the `time_offset` of the tof by measuring the position of the photon peak. Is there a way to fix this parameter and leave the other free in the energy calibration fit procedure?

**Comment by rettigl** [comment]
I think this is not implemented. There is a limit set on this parameter, I think, so adding some keywords and respective code for fixing parameters is certainly a good idea. Maybe also parameters to add starting values, right now they are kind of fixed, I think, or taken from the boundaries of the provided TOF range or so.

**Comment by steinnymir** [comment]
Ok, I'll try go through this and implement it within the HEXTOF calibration PR

**Comment by steinnymir** [comment]
Implemented in #169

**Comment by steinnymir** [comment]
cosed in #169
