### ISSUE TITLE
Issue with SED installation on Maxwell via Conda approach

### ISSUE THREAD

**Issue by potorocd** [OpenCOMPES/sed#212]
I installed SED on Maxwell to use the Tutorial notebook with test HEXTOF data using the 'Conda approach'. Simply following the installation doesn't lead to success. Here is a list of extra actions which were necessary for me:

1. To deal with virtual environments at the Maxwell cluster, I had to read this article ('conda activate' or 'conda init' doesn't work there):
https://rtd.xfel.eu/docs/data-analysis-user-documentation/en/latest/euxfel-software-environments/environments/
2. I could use env.yml once I removed 'locket==0.2.1' from the list of packages. Otherwise, it couldn't solve the environment.
3. List of packages which I had to install manually:
ipywidgets
fastdtw
lmfit
natsort
symmetrize
pynxtools
utils
4. To install a jupyter kernel ('python -m ipykernel install --user --name=sed_conda'), one also needs to install 'ipykernel'.
5. Eventually, I could load all modules with the required versions. However, there was an error: module 'pyarrow' has no attribute 'parquet'. I fixed it by using this hint:
https://github.com/modin-project/modin/issues/951

**Comment by rettigl** [comment]
@steinnymir Why actually using conda for the non-poetry installation approach rather than pip? This is not so python standard. 
In my view, a more consistent setup can be achieved with virtualenv, and pip install -e ., which actually does not require an additional file, but directly uses the pyproject.toml (we removed the requirements.txt at some point for this reason, and that's what the current workflows use). The ipykernel still needs to be installed, though, I think.

**Comment by steinnymir** [comment]
I totally agree. The conda approach is basically a residual from before poetry. `pip install -e .` would not have worked at the time, but should be the way to go now.

We should provide the commands to create an environment and then install with pip. Then we can still add ipykernel and the command to add the kernel to jupyter as an optional next step.

The conda approach, together with `env.yml` could be entirely removed.

We could also take the chance to move the setup instructions to the documentation page, where it should belong. We can make a link in the readme, and only leave a description of SED there.

**Comment by zain-sohail** [comment]
We should definitely provide pip installation as an option. Pip also allows to install extras which exist as notebook extras in the toml file.
I think it's quite common practice to have the installation details in the README.md and also the documentation. So we could link the README in the docs.

By the way, I yesterday helped someone new to dima's group to install sed and she just followed the steps on the README for poetry and took a min to install, just copying and pasting commands.

**Comment by rettigl** [comment]
This should now be obsolete, no?
