### ISSUE TITLE
ubid_offset

### ISSUE THREAD

**Issue by MichaelHeber** [OpenCOMPES/sed#230]
It seems like changing the ubid_offset does no change anything at the pulseId.

I would expect the electron distribution shifts if the ubid_offset is changed.

I was binning over the pulseId at the upper edge of the bunch train.
When I change the ubid_offset the edge did not shift to higher or lower positions.

![Screenshot from 2023-11-03 14-51-55](https://github.com/OpenCOMPES/sed/assets/74306453/0efe9cbd-ab04-4ed4-8cc8-072224de5ef2)
![Screenshot from 2023-11-03 14-52-55](https://github.com/OpenCOMPES/sed/assets/74306453/889ccfd7-7d1e-41af-b6dc-2942d5f23e59)

**Comment by steinnymir** [comment]
Yes, I would expect the same. @zain-sohail did you implement this in the loader?

**Comment by steinnymir** [comment]
Just to be sure, did you re-create the parquet files in between?
If this is done on the loader level, you might need to do so in order to have an effect.

**Comment by zain-sohail** [comment]
Yes, it stays the same as hextof processor before: 
https://github.com/OpenCOMPES/sed/blob/35bd2931bd57de127e0152f560000b8a056204ef/sed/loader/flash/loader.py#L240
https://github.com/OpenCOMPES/sed/blob/35bd2931bd57de127e0152f560000b8a056204ef/sed/loader/flash/loader.py#L364


> Just to be sure, did you re-create the parquet files in between? If this is done on the loader level, you might need to do so in order to have an effect.

Likely the cause, I guess #211 should also include checks for other loader related parameters being changed.

**Comment by zain-sohail** [comment]
I don't think there is a good way to check if the offset has changed (unless we somehow save that info in the buffer files).
Better is if we can do is provide the user an option to recreate the buffer (intermediate parquet) files

**Comment by steinnymir** [comment]
Well, this should be saved as metadata in the loading process. It could then be checked at least manually then.

This makes me wonder, how much metadata from the dataframe generation are we recording? None?
