### ISSUE TITLE
Adapt tof corrections for 4Q detector

### ISSUE THREAD

**Issue by steinnymir** [OpenCOMPES/sed#233]
refactor the code where necessary to make sure sector alignment works for the 4Q detector:

- [ ] aligning with 4 sectors only
- [ ] generate dldSectorId from geometrical position in dldPosX,dldPosY

**Comment by steinnymir** [comment]
AS the 4Q detector will not be used in the near future, this looses priority.

**Comment by zain-sohail** [comment]
I will close this since it won't be worked on in near future.
