### ISSUE TITLE
Upgrade python version

### ISSUE THREAD

**Issue by steinnymir** [OpenCOMPES/sed#247]
The latest release of python is now 3.12, which means our 3.8 is now 4 versions back, and we should consider upgrading.

I would not go all the way to 3.12 which was just released, but I'd rather push to 3.10.

according to https://devguide.python.org/versions/ 3.10 is now not recieving any updates rather than security, while 3.11 and 3.12 are still recieving bugfixes.

I tested 3.10 and at least for the hextof tutorial notebook and the tests, it worked just fine.

Also, I'm a big fan of 3.10, as it greatly improves readability of type hihts and their flexibility.
No need for Union or capitalized List Dict etc...
```python
def foo(x: int | list[int]) -> None:
   if not isinstance(x, int | float):
       raise ValueError()
```
There are also other performance improvements and a case funtion which is nice
https://docs.python.org/3/whatsnew/3.10.html

On the other hand:
> Python 3.11 is between 10-60% faster than Python 3.10. On average, we measured a 1.25x speedup on the standard benchmark suite. See [Faster CPython](https://docs.python.org/3/whatsnew/3.11.html#whatsnew311-faster-cpython) for details.

**Comment by rettigl** [comment]
I am absolute up for making sure our code is compatible with recent python version, so we should extend our multiversion tests accordingly. However, I would keep compatibility to python 3.8, because it is the default python shipped with many long-term support os-es, e.g. ubuntu 20.04, which has support until 2025.

**Comment by steinnymir** [comment]
I wonder if using the new features of python 3.10 would break compatibility with 3.8.
I have the feeling I did this and it worked, but i need to test to be sure

**Comment by zain-sohail** [comment]
Using the 3.10+ specific features definitely for example cause linting errors with other versions.
If we don't change the code, there shouldn't be any problem with moving to 3.10, as all our tests already show it works fine. That means that the dependencies we have are all compatible with 3.10.

**Comment by zain-sohail** [comment]
Just my comments. I am totally okay with moving to 3.10. We can change our linting workflow to adapt to it as well.

**Comment by steinnymir** [comment]
I tested functions using 3.10 functionalities in 3.8, and it obviously does not work... 😭 

We probably need to stick to developing in the oldest version we want to keep compatibility with, which is a pitty.
I would therefore propose we find really good reasons why to stick with 3.8 and not upgrade... the "its the default in an os" does not feel like a good enough reason to me.

**Comment by zain-sohail** [comment]
There only point regarding default on os is: The standard user on maxwell or any linux system (most users) will be having python 3.8 preinstalled. Then they just need to do pip install (or in their venv) to install sed. To have multiple python versions isn't that difficult but just additional steps for user. 

Though, just to counter that argument, users on systems other than linux are not exposed to the same python version e.g. on mac the default is 3.9

I don't think it's a necessarily strong argument

**Comment by steinnymir** [comment]
My favourite feature is the simpler type hints probably, but sure not worth big changes. 
I'd be curious about performance improvements, but those we should get by just using a more recent version, no need for extra features.

**Comment by zain-sohail** [comment]
So I think we are sticking with 3.8.

I'd suggest we update the toml file to at least allow for 3.11 (maybe 3.12 as well). We could of course add that to our tests.

**Comment by rettigl** [comment]
We could consider this:
https://stackoverflow.com/questions/63939138/is-there-a-way-to-use-python-3-9-type-hinting-in-its-previous-versions
