### ISSUE TITLE
Externally accessing flash public data (for docs)

### ISSUE THREAD

**Issue by zain-sohail** [OpenCOMPES/sed#251]
As the notebook is restricted to maxwell, we can not do the execution on github actions and put those changes in the documentation. Of course, we can have the notebook unexecuted but thought other solutions should be discussed.

Executing and putting it on the repo isn't a good idea as notebooks generally don't well with version control.

**Comment by rettigl** [comment]
The execution is not restricted to maxwell, only getting the data at the moment relies on the gamma portal. The example data are public anyhow. Why not putting them as well somewhere on Zenodo or so?

**Comment by zain-sohail** [comment]
I agree with that. @kutnyakhov what do you think?

**Comment by steinnymir** [comment]
> I agree with that

me to!

**Comment by zain-sohail** [comment]
Current update: Dima is still looking in into that

**Comment by kutnyakhov** [comment]
Finally, I've managed to upload and make it available on 
[Zenodo](https://zenodo.org/records/10658470)
Hopefully, I did it the right way :)

**Comment by zain-sohail** [comment]
Seems to be fine. I'll close this as completed.
