### ISSUE TITLE
linting errors

### ISSUE THREAD

**Issue by zain-sohail** [OpenCOMPES/sed#255]
I find the pylint configuration confusing because it doesn't catch many errors that it catches if you run it on a single file compared to the e.g. whole tests folder 
<img width="945" alt="Screenshot 2023-11-09 at 16 32 16" src="https://github.com/OpenCOMPES/sed/assets/10053031/e6032353-c09c-4a03-997d-5e7e9f2a4b45">

This error won't appear if i run it on the tests folder

Secondly, I propose we put pylint and mypy in the pre-commit config

**Comment by rettigl** [comment]
It used to find these kind of errors before. Maybe our linting does not work anymore correctly now with the new poetry setup (e.g. omitting tests)?
We can add pylint to pre-commit, but this will make it run slower. We can also indeed discuss to at least replace pylint by ruff, and keep mypy in addition.

**Comment by zain-sohail** [comment]
> It used to find these kind of errors before. Maybe our linting does not work anymore correctly now with the new poetry setup (e.g. omitting tests)? We can add pylint to pre-commit, but this will make it run slower. We can also indeed discuss to at least replace pylint by ruff, and keep mypy in addition.

I tested without using poetry and it still gives a code score of 10/10

But yes, ruff sounds like a better idea for replacement of pylint

**Comment by steinnymir** [comment]
I also found incosnistencies between how it is run in github and what it finds locally. Probably I did not set it up correctly, but having the check in the commit-hooks sounds great!

ruff seems to be an excellent choice for this, at least glancing at their website.

Shall we try adding `ruff` and `mipy` to commit-hooks `replacing black` and `flake8` (seems like ruff covers those...)?

**Comment by rettigl** [comment]
The reason for this is that in the respective folders, there is no __init__.py file, so it does not discover the files. See here:
https://pylint.pycqa.org/en/latest/user_guide/usage/run.html

**Comment by zain-sohail** [comment]
Ok so just by reading that and [this](https://github.com/pylint-dev/pylint/issues/2919), the solution is to include
`pylint ... sed tests/*`

We can first fix this and then move to ruff

**Comment by rettigl** [comment]
> Ok so just by reading that and [this](https://github.com/pylint-dev/pylint/issues/2919), the solution is to include `pylint ... sed tests/*`
> 
> We can first fix this and then move to ruff

I would rather say we should add the __init__.py files where missing...
Not sure what you suggested actually does what you think it does.

**Comment by zain-sohail** [comment]
Sorry that wildcard pattern indeed doesn't work but pylint ... sed tests/**/*.py does. Checked locally and it works.

I seem to get the impression that putting __init__.py isn't considered good practice by pytest https://pytest.org/en/7.4.x/explanation/goodpractices.html and this is quite old but read it here too: https://github.com/pyscaffold/pyscaffold/issues/52

But perhaps this is a better fix

**Comment by zain-sohail** [comment]
Sorry that wildcard pattern indeed doesn't work but pylint ... sed tests/**/*.py does. Checked locally and it works.

I seem to get the impression that putting __init__.py isn't considered good practice by pytest https://pytest.org/en/7.4.x/explanation/goodpractices.html and this is quite old but read it here too: https://github.com/pyscaffold/pyscaffold/issues/52

But perhaps what you suggest is a better fix

**Comment by steinnymir** [comment]
We had some discussions about adding or not __init__.py in the tests folders, and we decided not to, based on the link you sent. Basically does not mess up your name space for local testing...

**Comment by zain-sohail** [comment]
The method I suggest in PR #261 does work. If approved, I will merge to main.

**Comment by rettigl** [comment]
> We had some discussions about adding or not **init**.py in the tests folders, and we decided not to, based on the link you sent. Basically does not mess up your name space for local testing...

We have these files essentially everywhere, so I don't understand this comment. If they are removed, the functions from the helper files cannot be imported anymore. I don't see an immediate need to change the way things work right now, and would rather suggest to add the init files to the new test folders, but the fix in PR #261 is also fine. It's just unnecessary if you add the init files.

**Comment by zain-sohail** [comment]
I will close this issue then. You're right in that we can just add the init file
