### ISSUE TITLE
SXP Loader

### ISSUE THREAD

**Issue by zain-sohail** [OpenCOMPES/sed#263]
In lieu to the short email discussion, there is a lot of similarity in data structure at flash and xfel's SXP. Some few key differences are there.

- how at flash, the group datasets only contain index, value or time but it differs at SXP
- the multiindexing likely differs
- etc (please add) 

This issue is to figure out what code is common and to refactor the code in such a way that the common functionality is seperated. Where that common functionality should exist is yet to be discussed. 

Side note: The lab at CFEL next to flash also uses a very similar data layout, but still differs. So it too would need the common features.

**Comment by zain-sohail** [comment]
please move to discussions if necessary

**Comment by rettigl** [comment]
I started working on this in PR #264. Basic loading seems to work now, but microbunch index still missing.

**Comment by zain-sohail** [comment]
I saw the git blame and the code indeed is very similar. 

I think opening a new issue to refactor Flashloader in such a way that it works for pg2 at flash (hextof and wespe), lab at cfel and sxp.

I can see it being done by seperating these functionalities (non-exhaustive):

- Multiindex behavior
- Metadata handling (already seperate)
- The dataframe parquet file loading/saving (probably should be part of core features) 
- Buffer file handling
- config file and schema loader (where schema has the definitions which we give to each vocabulary in use in config) 
- Likely to have index and dataset as seperate values in the channels key
- filling nan method is already seperated

Then all that's left in the flashloader is to load and concat the data.

**Comment by zain-sohail** [comment]
I think with what David sent in the email, probably better to use https://github.com/European-XFEL/EXtra-data to load data into sed than to repurpose flash loader. 
I think earlier it just wasn't known that they already have a data loader.

**Comment by rettigl** [comment]
Not sure I see a benefit in this. What I have now works more or less, once I implement the correct microbunchId readout. I won't have time to invest more into this, but feel free to write another reader from scratch...

**Comment by zain-sohail** [comment]
As you were saying, that it'd be added burden to maintain both loaders so I thought this'd have made more sense. 
But implementing it isn't a priority from our side either. I will close this issue but if @daviddoji has thoughts, he can reopen again.
