### ISSUE TITLE
Include time-stamped external data

### ISSUE THREAD

**Issue by steinnymir** [OpenCOMPES/sed#27]
Function to interpolate and map time-stamped external data into the data frame based on the time stamps of the data.

FHI already has some code, but needs to be wrapped into a function.

**Comment by steinnymir** [comment]
@rettigl did we implement something in this direction?

**Comment by rettigl** [comment]
Not yet, but We have code ready for this. I have this on my agenda for quite some time.

**Comment by rettigl** [comment]
Addressed in #227
