### ISSUE TITLE
FLASH loader failing when h5 channel exists but is empty

### ISSUE THREAD

**Issue by steinnymir** [OpenCOMPES/sed#299]
Fix bug in data loading which crashes the loader when an empty hdf5 file is being loaded.

**Comment by zain-sohail** [comment]
> Fix bug in data loading which crashes the loader when an empty hdf5 file is being loaded.

Can you give me an example empty hdf5 file? I can't recreate the bug scenario without knowing the appropriate structure, and write appropriate tests/handling for it.
