### ISSUE TITLE
(Unified) schema for the config file

### ISSUE THREAD

**Issue by zain-sohail** [OpenCOMPES/sed#302]
Currently it's really hard for users and even developers to know what goes in the config file. Like which parameters are being used and which not.

Hence, we need to define a schema so that the available keys and their meanings can be understood.

In addition, if we can unify especially the common things in the loaders to similar keys, that'd be ideal. One example is the channel list (group names and keys) and aliases that differ in all loaders. 

Once we have a schema, which we can define using jsonschema (or others), we can validate everytime during parsing config if it is valid.

Problems I see if we do this: The older config files might become unusable so a way has to be figured on how to work with that. Or maybe we just introduce the newer config file schema in v1.0.0

**Comment by zain-sohail** [comment]
#330 partly covers this. The old config files can still be used.

For MPES to use this config model, they'd need to adhere to the channels subsection currently in use by flash and sxp loader.

**Comment by zain-sohail** [comment]
We would also like to document which functions make use of which config parameters. Not sure if it's possible to do with pydantic alone but should be looked into.

This is useful for new users to know what is possible to configure

**Comment by rettigl** [comment]
> We would also like to document which functions make use of which config parameters. Not sure if it's possible to do with pydantic alone but should be looked into.
> 
> This is useful for new users to know what is possible to configure

This is already documented at many places in the docstrings (i.e. as defaults)

**Comment by rettigl** [comment]
Addressed in #487
