### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by steinnymir** [OpenCOMPES/sed#32]
Find a good method to automise the creation of the documentation page.

Also, we need to fix the commenting style to use when commenting code. Suggestions?

**Comment by daviddoji** [comment]
AFAIK, documentation is created from .rst files and built automatically with sphinx

**Comment by zainsohail04** [comment]
> AFAIK, documentation is created from .rst files and built automatically with sphinx

You're right. We're just thinking if there is a more automated way to document. Sphinx does have autodoc which I think is good to use. I was thinking if the type hints can be incorporated somehow and it seems sphinx extension Napoleon might be able to do it
