### ISSUE TITLE
reset index doesn't work as expected

### ISSUE THREAD

**Issue by zain-sohail** [OpenCOMPES/sed#320]
Since dask is handling the partitions, the reset index works only on individual partitions. I don't think this is critical for binning but for users who want to slice part of dataset. 

![image](https://github.com/OpenCOMPES/sed/assets/10053031/1b7579b8-5191-48d4-9757-bfe69aeab528)

**Comment by rettigl** [comment]
I don't see the problem. There is the option to select both individual partitions (or slices/ranges thereof) with the df_partitions parameter, and you can select a subset of events per partition with the filter functions. What else are you missing?

**Comment by zain-sohail** [comment]
Say, I want to select a range which spans multiple partitions e.g. 900000-1200000. But once can only filter on these indexes if they are correct. Perhaps I miss something.

**Comment by rettigl** [comment]
What use case for such a query do you have in mind? If you are interested in a certain consecutive range, I'd rather select on timeStamp, or on MacroBunchId, if available. Otherwise selection per partition should be sufficient.

**Comment by rettigl** [comment]
You can also do something like this:
```
ddf['id'] = 1
ddf['id'] = ddf.x.cumsum()
```
and then filter on this...

**Comment by zain-sohail** [comment]
> What use case for such a query do you have in mind? If you are interested in a certain consecutive range, I'd rather select on timeStamp, or on MacroBunchId, if available. Otherwise selection per partition should be sufficient.

I basically wanted to get subsets of the data to create sort of a training set for a denoising DL algorithm. But your idea sounds good.
I saw they also have a sample method and think that that should also be fine for my purpose.
