### ISSUE TITLE
ValueError('cannot insert trainId, already exists')

### ISSUE THREAD

**Issue by daviddoji** [OpenCOMPES/sed#339]
**Describe the bug**
When trying to load some runs from a recent proposal taken at the SXP instrument ("/gpfs/exfel/exp/SXP/202302/p004316/raw/"), the SedProcessor complains with the error seen in the screenshot.

![image](https://github.com/OpenCOMPES/sed/assets/4411314/639c9521-fdf3-4fb6-90c1-ee2a082f5721)

**To Reproduce**
1. Spawn a node in the Maxwell cluster.
2. Create a new virtual environment by cloning the last version of the repository (v0.1.7)
3.  Open the tutorial notebook for SXP (tutorial/5_sxp_workflow.ipynb)
4. Change path for the context file and choose a folder with proper write permissions for the generation of parquet files
5. Execute the SedProcessor 

**Expected behavior**
A `SedProcessor` object is created.

**Comment by rettigl** [comment]
Can you specify:
1. What do you mean by "spawn a note in the cluster"? Using the jupyter hub max-jhub.desy.de? Which maxwell partition and which python version did you use?
2. cloning the repository does not create a virtual environment. How did you do this? Poetry? Did you create a new kernel for this?
4. Which config file did you use (you write you changed the path...)
5. Which exact commands did you execute in the notebook?

**Comment by daviddoji** [comment]
> Can you specify:
> 
>     1. What do you mean by "spawn a note in the cluster"? Using the jupyter hub max-jhub.desy.de? Which maxwell partition and which python version did you use?
When you go to max-jhub.desy.de, one request a node that gets spawned. I used the exfel partition, but that should not matter.
> 
>     2. cloning the repository does not create a virtual environment. How did you do this? Poetry? Did you create a new kernel for this?
True, sorry for that. I created a venv using the `--system-site-packages` flag from the module `exfel-python` to avoid potential issues regarding plotting in maxwell, as documented in [here](https://rtd.xfel.eu/docs/data-analysis-user-documentation/en/latest/euxfel-software-environments/maintenance/environments/?h=module#faq) and [here](https://rtd.xfel.eu/docs/data-analysis-user-documentation/en/latest/euxfel-software-environments/maintenance/environments/?h=module#faq) by doing the following:

```
module load exfel exfel-python
python -m venv --system-site-packages sed
source ./sed/bin/activate
```
Once the venv was activated, I just cloned the repository and just pip install it. I also created a kernel for the venv, which I used to run the notebook.
 
> 
>     3. Which config file did you use (you write you changed the path...)
I used the config file for SXP provided with the repository. I only changed the path to it because the tutorial `5_sxp_workflow.ipynb` could not find it, as it is currently written.
> 
>     4. Which exact commands did you execute in the notebook?
I just run the first three cells, getting the error mentioned above.

**Comment by rettigl** [comment]
I tried to follow your steps, but failed at the first one, because I don't see the exfel partition. Also the second one does not work, because the command
`module load exfel exfel-python`
fails. So I created a new python environment without that. I also had to omitt the `--system-site-packages` because that provided incompatible package versions.

I installed  a new enviroment, and installed sed there in editable mode.

```
[rettigla@max-exfl096]~/sed_tests% python -m venv sed_pyenv 
[rettigla@max-exfl096]~/sed_tests% source ./sed_pyenv/bin/activate
(sed_pyenv) [rettigla@max-exfl096]~/sed_tests% cd sed
(sed_pyenv) [rettigla@max-exfl096]~/sed_tests/sed% pip install -e .
...
(sed_pyenv) [rettigla@max-exfl096]~/sed_tests/sed% python -m ipykernel install --user --name=sed_test  
Installed kernelspec sed_test in /home/rettigla/.local/share/jupyter/kernels/sed_test
```

Then I executed the tutorial 5. The only thing I modified was the data_parquet_dir, to make sure to use a non-existing folder. The config file was found without problem, and everything runs as expected. 
![grafik](https://github.com/OpenCOMPES/sed/assets/53396064/d49cc04a-1d23-4f21-9d63-205ab40cc1fc)
I cannot reproduce your problem, and suggest you try the way I describe here.

**Comment by daviddoji** [comment]
I'll give it a try and will close the issue if I don't find any issues. Thx a lot @rettigl

**Comment by daviddoji** [comment]
I managed to make it work with a bit of work. I'll close the issue. Thx again @rettigl !

**Comment by rettigl** [comment]
Good to hear it works now. If you have some insight into what the problem was, that might, however, be helpful for other users running into the same issue...

**Comment by daviddoji** [comment]
I would guess that it was due to incompatibility of versions in some packages. By default, I load several modules in Maxwell that may collide with the requirements you asked for sed.
Creating a vanilla venv, one can make it work ;)
