### ISSUE TITLE
Problem with get metadata from SciCat

### ISSUE THREAD

**Issue by kutnyakhov** [OpenCOMPES/sed#345]
Get metadata from scicat using ingestor login and the password is not functioning after scicat was migrated to the new backend.
With the help of IT guys, I could adopt /sed/sed/loader/flash/metadata.py file to use my own token generated by SciCat.
Also config.yaml file has to be changed with metadata:scicat_token:"eyJhbGciOi...." #copied from the SciCat front-end webpage (User/Settings/SciCat Token).
Thus: 
- pros - no need to make public credentials of ingestor;
- cons - token is not a long leaving thing (probably just a few hours) and has to be recopied from SciCat
Somehow I didn't manage to push changes to github directly, so metadata file is attached.
[metadata.txt](https://github.com/OpenCOMPES/sed/files/14345312/metadata.txt)

**Comment by rettigl** [comment]
This is probably something to discuss with the admins of that server. How is it handled for automatic igestion, e.g. from the DAQ? What account is being used there? A r/o accound would be sufficient for our use case. If there is no permanent solution, then maybe a cell that sets the respective config item in a template notebook would be a good idea, where users can copy paste their Token.

**Comment by kutnyakhov** [comment]
I was trying to make the local branch get-metadata-from-scicat-using-token and push it on github, but got 403 error :)

Concerning lifetime - let's see what will be an answer from scicat guys, but I could not find any easy set for this via the web interface.

**Comment by zain-sohail** [comment]
> I was trying to make the local branch get-metadata-from-scicat-using-token and push it on github, but got 403 error :)

It seems you weren't having write permissions. I have added you now. But otherwise, I also made a PR #347 to address what you put

**Comment by zain-sohail** [comment]
Now the token can be added as a keyword argument when calling the sed processor.

**Comment by kutnyakhov** [comment]
After discussing with ITs, it seems that we can also use the build conda package for SciCat
conda install -c https://hasfcpkg.desy.de/doocsconda scicat
which already exists as the default package inside of the "flash" kernel on Maxwell.
It still uses ingestor credentials to get metadata, but it also has the power to ingest/update metadata inside SciCat.
This way we can do:
- from scicat import ScicatClient
- scicat_ingestor = ScicatClient(proposal_id, source_folder)
- run_info = scicat_ingestor.get_dataset(runNumber)

This way we don't need to worry about refreshing the token every time you want to read metadata and also no danger of spreading credentials around, but for sure it opens a way to mess up something within SciCat if someone decides to ingest/update existing data - in this case, there is still version tracking and history available from SciCat side.

Another good side of that package is that everyone will be able to create a run summary table at any time:
scicat_ingestor.create_csv_run_table(filepath)

**Comment by zain-sohail** [comment]
Preferably, ingesting should be seperated from fetching the metadata. As you said, with the Scicat package, the users can ingest data and update something. I'd suggest the ingestor is used during beamtimes but for later, the users should use their own credentials to fetch metadata (The branch is merged to main now)

The run summary table sounds interesting. Probably a fix to the question we had about fetching metadata for multiple runs at once?
