### ISSUE TITLE
Catch illegal kwds arguments

### ISSUE THREAD

**Issue by rettigl** [OpenCOMPES/sed#363]
Catch and report all illegal kwds arguments in all relevant functions

**Comment by zain-sohail** [comment]
How is illegal being defined?
We would nee dsome sort of schema to check that.

**Comment by rettigl** [comment]
Any function that accepts **kwds should filter them depending on where they are passed to. This only becomes relevant, if you pass **kwds to a function that does not accept **kwds. Then you must ensure that only legal keyword arguments are being passed.

**Comment by zain-sohail** [comment]
So there are two cases?

- **kwds are passed but shouldn't be
- **kwds are legal but some illegal ones are also passed

So I am guessing legal ones are the ones that pass the check inside the function/method?

Not sure how to approach this issue. One way would be to add decorator to each method but that doesn't seem ideal.
The other is to just perform this check at testing phase.

**Comment by rettigl** [comment]
Closed by #466
