### ISSUE TITLE
Use standardized directories

### ISSUE THREAD

**Issue by zain-sohail** [OpenCOMPES/sed#403]
To promote sed as a proper application, it's ideal if the user config files/data/logs be saved in OS specific standardized directories. 

`platformdirs` provides such functionality and can be used to save user configs and other data, if user doesn't specify where to put them. 
Logs can also be saved in the user log directory so when there are bugs, user can just provide us the log file.

**Comment by rettigl** [comment]
We can discuss if this is a good change with respect to the current setup, which does something similar already for the user_config and system_config. 
I am affraid it might make it more difficult to find the relevant files. If we decide to go this route, it must be thorougly reflected in the documentation.

**Comment by rettigl** [comment]
In particular, I see this problematic for data files, which are large, and might end up on locations the user is not aware off.

Additionally, I suggest to keep log files together with the notebooks. We are not building an application with a single running instance here, but a class to be executed in notebooks. If we have just one log file, entries from different sources get mixed together, and might even lead to access conflicts.

**Comment by zain-sohail** [comment]
> In particular, I see this problematic for data files, which are large, and might end up on locations the user is not aware off.

When it comes to the datasets being fetched from zenodo, I find the data being in one standard place a big plus.
We should definitely introduce a option to delete the dataset (The user can already do it since the path is given when data is read). 
This was a big problem for me, since I have multiple instances of sed (repo clones and packaged instances) and I have no way to keep track of where I downloaded which datasets. Right now the datasets module only tracks one place where data is downloaded/stored, but it should be extended.

One common ground could be that we provide option to store in "default" directories but the user has to allow that?

> Additionally, I suggest to keep log files together with the notebooks. We are not building an application with a single running instance here, but a class to be executed in notebooks. If we have just one log file, entries from different sources get mixed together, and might even lead to access conflicts.

That's true. Your suggested option can definitely be the default. But we want to slowly approach more autonomous workflow, and for that I propose keeping the logs in standard dirs.

Just for remembering. This would be a good format for debugging as it gives filepath and lineno.
`format="%(asctime)s [%(levelname)s]: %(message)s in %(pathname)s:%(lineno)d",`

**Comment by zain-sohail** [comment]
I have changed the beahvior to download datasets in current working directory. Likewise, log files are logged there.
The only usage of standard directory is for the datasets.json file which keeps track of the paths where user has downloaded datasets.

**Comment by rettigl** [comment]
Sounds good, I will test this some time later this week
