### ISSUE TITLE
Add nexus definitions for hextof in the repo

### ISSUE THREAD

**Issue by zain-sohail** [OpenCOMPES/sed#417]
[NXmpes_config-HEXTOF_full_Feb2024-1.json](https://github.com/user-attachments/files/15840175/NXmpes_config-HEXTOF_full_Feb2024-1.json)

Here's the definiton provided by @kutnyakhov . Might need updating.

**Comment by zain-sohail** [comment]
Should also save the processing steps in the file because currently they are not available when exported to nexus.

**Comment by rettigl** [comment]
> Should also save the processing steps in the file because currently they are not available when exported to nexus.

Yes, the processing metadata are mostly also still missing for mpes. Would be good to create also an example for the documentation for this, if possible (not sure how to handle the SciCat part there, however).

**Comment by zain-sohail** [comment]
> Yes, the processing metadata are mostly also still missing for mpes. Would be good to create also an example for the documentation for this, if possible (not sure how to handle the SciCat part there, however).

So you mean we create a documentation of how to make your nexus definition json? I am not fully sure how since Dima did it but I can take a look.

Regarding Scicat, DESY users should be able to access scicat with their account and get a token.
For documentation, we can provide the json file that scicat returns.

**Comment by rettigl** [comment]
I opend a PR for discussion of this: #420
