### ISSUE TITLE
PackageNotFoundError on the main branch

### ISSUE THREAD

**Issue by kutnyakhov** [OpenCOMPES/sed#460]
**Describe the bug**
What I've mentioned today during meeting:
during calling from sed import SedProcessor I am getting a PackageNotFoundError while I am using main branch.
This is not a case if I am using e.g. update-hextof-tutorial branch

**Screenshots**
Here is an error itself
![PackageNotFoundError](https://github.com/OpenCOMPES/sed/assets/38926659/6853363e-883f-42f6-b7f3-40c0f7d928af)

**Comment by rettigl** [comment]
How did you install the package? As described here? https://github.com/OpenCOMPES/sed/blob/main/README.md#for-contributors-pip
What is the output of ` pip list | grep sed-processor`
It should look something like 
```
rettig@pcr840:..sed/sed> pip list | grep sed-processor
sed-processor                 0.1.10a5            /mnt/pcshare/users/Laurenz/AreaB/sed/sed
```

**Comment by kutnyakhov** [comment]
This particular kernel was installed using poetry approach.
In my case, output is empty line.

**Comment by rettigl** [comment]
Ah, you are using the kernel approach, and don't activate the environment. I never tested this, @zain-sohail please check.

**Comment by zain-sohail** [comment]
And `poetry install` was also run? This should usually install sed-processor package. 

I am running the latest v1_feature_branch (it's up to date with main as well) using poetry as well and have no issues.

**Comment by rettigl** [comment]
> This particular kernel was installed using poetry approach. In my case, output is empty line.

Can you do `poetry run pip list | grep sed-processor`

**Comment by kutnyakhov** [comment]
> > This particular kernel was installed using poetry approach. In my case, output is empty line.
> 
> Can you do `poetry run pip list | grep sed-processor`

It also returns empty line

**Comment by rettigl** [comment]
Can you then please go through the installation steps once more? It appears the packages is not properly installed.

**Comment by kutnyakhov** [comment]
The new installation helped and also `poetry install` in the old installation helped as well.
And now `poetry run pip list | grep sed-processor` returns:
sed-processor                 0.1.10a5           /home/kutnyakd/sed
Thanks for help :)

**Comment by zain-sohail** [comment]
We figured the problem that 
`pip install -e .[all]` doesn't work but 'pip install -e .' does to install in editable mode.
