### ISSUE TITLE
Purging notebook file history

### ISSUE THREAD

**Issue by zainsohail04** [OpenCOMPES/sed#53]
So similar to removing h5 files once upon a time in hextof-processor, I have purged and rewritten (and pushed) the old commits of the notebooks since they contained the output, adding up to a big portion of the repository codebase. 
I do have a backup in case it led to some intended consequences. If it is looking good, please pull a fresh copy of the repo. Otherwise, it will reset the history.
Currently, not sure why it still shows 20% Jupyter notebook source code. I couldn't purge the deleted branches so it could be that.

**Comment by steinnymir** [comment]
I think 20% notebooks is not completely unrealistic, as we only really have the binning functions out there so far...
In any case, I had not noticed the notebooks were taking up so much, but if the purging helped, good!

**Comment by zainsohail04** [comment]
> I think 20% notebooks is not completely unrealistic, as we only really have the binning functions out there so far... In any case, I had not noticed the notebooks were taking up so much, but if the purging helped, good!

Yea that is also correct. If need be, we are supposed to contact github support to remove the history from PR branches.
