### ISSUE TITLE
Benchmark notebooks

### ISSUE THREAD

**Issue by rettigl** [OpenCOMPES/sed#60]
Getting back to Steinn's comment in the test data set pull request:

"- I very much liked the comparison with the mpes binning, which showed a slower performance of sed compared to the original mpes. I don't know where this comes from, might be worth lookin into!"

I suggest it would be a good idea (at least for us) to make some benchmarks and tests to run for this code and compare to other binning code, to keep track of what our changes to the code to with the performance.
I actually had a different impression, that the sed code performed either very similar, or slightly better compared to the mpes binning (without jitter). Turning on jitter made mpes much slower, though. 
I had the experience that the very first time you run a binning in an instance of a kernel is slower than the subsequent runs, so it might be required to repeat tests.

**Comment by daviddoji** [comment]
In Jupyter, one can use the `%timeit` magic to benchmark a single function/line within a cell or `%%timeit` to benchmark the entire cell.

These magic commands execute the code several times and give some statistics about execution time.

**Comment by rettigl** [comment]
PR #120 includes a benchmark notebook
