### ISSUE TITLE
test_from_bins_equals_from_bin_range() failing from time to time

### ISSUE THREAD

**Issue by rettigl** [OpenCOMPES/sed#67]
**Describe the bug**
The test function test_from_bins_equals_from_bin_range() fails from time to time with an assetion error:
```
./sed/tests/test_binning.py::test_from_bins_equals_from_bin_range Failed: [undefined]AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 2 / 87210 (0.00229%)
Max absolute difference: 4294967295
Max relative difference: 4.2949673e+09
 x: array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],...
 y: array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],...
def test_from_bins_equals_from_bin_range():
        H1 = _hist_from_bin_range(sample3d, bins3d, ranges3d)
        H2 = _hist_from_bins(sample3d, arrays3d, tuple(b.size for b in arrays3d))
>       np.testing.assert_allclose(H1, H2)
E       AssertionError: 
E       Not equal to tolerance rtol=1e-07, atol=0
E       
E       Mismatched elements: 2 / 87210 (0.00229%)
E       Max absolute difference: 4294967295
E       Max relative difference: 4.2949673e+09
E        x: array([[[0, 0, 0, ..., 0, 0, 0],
E               [0, 0, 0, ..., 0, 0, 0],
E               [0, 0, 0, ..., 0, 0, 0],...
E        y: array([[[0, 0, 0, ..., 0, 0, 0],
E               [0, 0, 0, ..., 0, 0, 0],
E               [0, 0, 0, ..., 0, 0, 0],...

sed/tests/test_binning.py:47: AssertionError
```

The number looks like an overflow error. Is this related to the different histogram behavior reported in #66?
**To Reproduce**
Execute the test mutliple times.

**Expected behavior**
The test should run through always

**Screenshots**
n/a

**Additional context**
We should adopt the test function to restrict the

**Comment by steinnymir** [comment]
I also noticed it fails only some times. I believe it to be caused by the bug reported in #66. It is interesting however that the binning is not consistently different... I'll try look into it when I find time.

**Comment by daviddoji** [comment]
@rettigl are you using the packages installed by Poetry? If not, which Python and Numpy versions were used to produced the error?

**Comment by daviddoji** [comment]
> I also noticed it fails only some times. I believe it to be caused by the bug reported in #66. It is interesting however that the binning is not consistently different... I'll try look into it when I find time.

that's why a reproducible environment is so important :)

**Comment by steinnymir** [comment]
it seems to have nothing to do with the environment. Running it again on the same machine and same environment gives different result. The only thing changing is the seed of the RNG which creates the data.

The bug might be in data overflow, as @rettigl suggested. But I cannot yet understand why.

**Comment by daviddoji** [comment]
is the error still appearing with a fix seed?

**Comment by rettigl** [comment]
> @rettigl are you using the packages installed by Poetry? If not, which Python and Numpy versions were used to produced the error?

I could not get the poetry thing to work, and needed an environment where also mpes was installed, so I did it manually using the requirements file with pip. I also installed the package for nexus conversion, which has conflicting package versions pinned, and therfore might have installed some other package versions. This is one of the reasons I don't like fixed package versions...

I am using Python 3.8.12
and numpy 1.21.5

**Comment by daviddoji** [comment]
> > @rettigl are you using the packages installed by Poetry? If not, which Python and Numpy versions were used to produced the error?
> 
> I could not get the poetry thing to work, and needed an environment where also mpes was installed, so I did it manually using the requirements file with pip. I also installed the package for nexus conversion, which has conflicting package versions pinned, and therfore might have installed some other package versions. This is one of the reasons I don't like fixed package versions...
> 
> I am using Python 3.8.12 and numpy 1.21.5

Are you using a local machine or are you using a cluster? If you have access to Maxwell, I can show you how to do it there (and how to install any additional packages that you need)

**Comment by rettigl** [comment]
I'm not sure if I still have access to the Maxwell cluster. I am running this on our local compute node at FHI. Maybe we can have a meeting where you show this to all interested next week to so.
A general remark to the tests: 
It appears to me that mostly the tests not bin any events. You define random events that are normal distributed around 0 (that's what randn does), and then you bin the interval [1, 2]. So mostly outlierts will end in your binned range...

**Comment by daviddoji** [comment]
> I'm not sure if I still have access to the Maxwell cluster. I am running this on our local compute node at FHI. Maybe we can have a meeting where you show this to all interested next week to so. A general remark to the tests: It appears to me that mostly the tests not bin any events. You define random events that are normal distributed around 0 (that's what randn does), and then you bin the interval [1, 2]. So mostly outlierts will end in your binned range... If I change the ranges to [-1,1], the test essentially never works.

Sure. Next week only Thursday will work for me.

**Comment by rettigl** [comment]
My testing so far concludes that the binsearch function does not work properly. I remember you had some discussion in this direction already, but why not use np.digitize for this? This seems like exactly the use case you need here, and is supported by numba... (?)

**Comment by rettigl** [comment]
No, does not seem to be true. The two functions return do the same. Still we could use the digitize function...

**Comment by rettigl** [comment]
It seems to be to be related to the way the two functions treat the bins and edges. In the one case, you explicitly define edges, in the other case you define bin (centers), and there is in fact one edge more...

**Comment by steinnymir** [comment]
> My testing so far concludes that the binsearch function does not work properly

I would not be too surprised about that. we should try substitute with np.digitize, as you suggested, or np.searchsorted, which according to the documentation should be marginally faster, and supports any dtype. If they work with numba, numpy implementations are always a better bet than my home-made scripts.

**Comment by daviddoji** [comment]
By using the `poetry shell` environment as described in the README, I've run the tests for more than 10 times and I could not reproduce this issue
