### ISSUE TITLE
Move default values into default config

### ISSUE THREAD

**Issue by rettigl** [OpenCOMPES/sed#92]

**Comment by zainsohail04** [comment]
Could you please look into this? This would be a great start to a user documentation since I am also not clear as of now what parameters can or do go in the config file and which don't. 
A guideline for the config would be well appreciated too. I can then set it up with doc building.

**Comment by rettigl** [comment]
This depends a little bit on what we consider the default should do/be. I think this is something we should discuss in a meeting.

**Comment by rettigl** [comment]
This is addressed in PR #131
