### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by zainsohail04** [OpenCOMPES/sed#99]
The automated documentation is not being properly built currently since the right parameters are not provided.

But more importantly, the library has a lot of modules and information so guiding the user through something other than notebooks is also useful. For example, on how to set up a config file for their usecase. 

For developers:
We should provide a documentation for how to implement a loader plugin.

**Comment by steinnymir** [comment]
I totally agree that a proper documentation page is required.
There are many modules doing different things that are not even clear to me, so I can only imagine for external users.

Maybe we should discuss how to do this, and who should take care of which section.

**Comment by zainsohail04** [comment]
I have a few ideas on how to document (after the workflow manager concept is included), so I will assign this task to myself.

**Comment by rettigl** [comment]
PR #106 fixes the autodoc generation and docstrings for the current workflow modules. Metadata is omitted, because it is mostly still empty, and I do not really understand how it is supposed to work.

**Comment by rettigl** [comment]
Closed by PR#106
